CATEGORY_BLACK_LIST = ['Sport', 'Music', 'Homo sapiens', 'Location (geography)', 'Television', 'Weather', 'Science',
                       'Technology', 'Science, technology, engineering, and mathematics', 'Sex', 'Art', 'Book', ]

ENTITY_BLACK_LIST = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
                     'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                     'November', 'December',
                     'Jews', 'Feces', 'Swine', 'Devil',
                     '2019–20 coronavirus outbreak',
                     'Bible', 'Quran', 'Gospel', 'Christianity' #religious texts
                     'HTTP cookie',
                     'Health', 'Business', 'Entertainment', 'Science', 'News', # general stuff from News
                     'Film', 'Labor',
                     'Labor theory of value', #what??
                     'Donald Trump (song)',
                     'Soccer (dog)',
                     'Legacy system', 'Legacy game', 'Left-wing politics', 'Left-right political spectrum',
                     'Left-libertarianism', 'American Left', 'Working memory',
                     'Gender transitioning',
                     'Girlfriend', 'Boyfriend', 'Husband', 'Wife', 'Father', 'Mother', 'Son', 'Daughter', 'Stepchild', 'Cousin'
                     ]

ENTITY_BLACK_LIST += [
    "Film",
    "Musical instrument",
    "Music",
    "Television",
    "Animal",
    "Travel",
    "Celebrity",
    "Musician",
    "Food",
    # "Dog",
    # "Cat",
    "School",
    "Sport",
    "Book",
    "Video game",
    "Mathematics",
    "Supernova",
    "Song",
    "Library",
    "Horror film",
    "Color",
    "Education",
    "Love (2015 film)",
    "Drum kit",
    "Reading",
    "Car",
    "Manna",
    "Friends",
    "Art",
    "Mom (TV series)",
    "Fish",
    "Science",
    "Dance",
    "Astronomy",
    "History",
    "Relax (song)",
    "Technology",
    "Pet",
    "Health",
    "The Move",
    "Business",
    "Music (Madonna song)",
    "Entertainment",
    "Restaurant",
    "Planet",
    "Bird",
    "Love",
    "Human",
    "Politics",
    "Remember (2015 film)",
    "Life (2017 film)",
    "I Wanna (Marie N song)",
    "Mommy (2014 film)",
    "Wanna, Pakistan",
    "Politics (Aristotle)",
    "Cooking",
    "Friends (2001 film)",
    "Favourite",
    "Favorite Channel",
    "Good (film)",
    "Toy",
    "YouTuber",
    "Nitric oxide",
    "Time",
    "Mama (2013 film)",
    "Suicide Squad (film)",
    "Cat meat",
    "Plot (narrative)",
    "Robbery",
    "Love & Basketball",
    "Snack",
    "Taste",
    "Chicken as food",
    "Vegetable",
    "Timer",
    "Soccer (dog)",
    "Dog (zodiac)",
    "Fashion",
    "Kitten",
    "Going-to future",
    "Puppy",
    "Cartoon",
    "Robots (2005 film)",
    "Toy Story",
    "Cousin",
    "Joke",
    "Friday (1995 film)",
    "Cry (Godley & Creme song)",
    "Ping Pong (2002 film)",
    "Big (film)",
    "Delicious (TV series)",
    "Flavor",
    "Quarantine (2008 film)",
    "House (TV series)",
    "Yes (band)",
    "Awesome (window manager)",
    "Place (United States Census Bureau)",
    "Fuller House (TV series)",
    "Recess (TV series)",
    "David",
    "I Don't Wanna (Aaliyah song)",
    "Fun (band)",
    "Heroes (1977 film)",
    "Meat",
    "Today (American TV program)",
    "Spontaneous (film)",
    "29er (bicycle)",
    "Dog meat",
    "Airplane!",
    "Victorious",
    "Weather",
    "Park",
    "Kids (film)",
    "CKE Restaurants",
    "Mask",
    "Universe",
    "A.I. Artificial Intelligence",
    ".travel",
    "Mobile app",
    "President of the United States",
    "Ghost (Swedish band)",
    "Robbery (Juice Wrld song)",
    "Vacation (The Go-Go's album)",
    "Nice",
    "Echo (mythology)",
    "God",
    "Emotion",
    "Online and offline",
    "Michael",
    "Sugar",
    "Scratch (programming language)",
    "Dude",
    "News",
    "Evil (wrestler)",
    "Calm (album)",
    "Place (Reddit)",
    "The Sound of Music (film)",
    "Horror fiction",
    "America (band)",
    "Favorite (Loona song)",
    "Kawaii",
    "I Wanna Know (Joe song)",
    "Hectare",
    "Racism",
    "Heroes (American TV series)",
    "Music (2021 film)",
    "Sophie (musician)",
    "Basketball (The Office)",
    "Aegyo",
    "Dead (musician)",
    "James (band)",
    "Drawing",
    "Nap",
    "Snake (zodiac)",
    "Anna (2019 film)",
    "I Am (2010 Indian film)",
    "Money",
    "The Ocean (band)",
    "Science (journal)",
    "Don't Be Cruel (album)",
    "Mars (mythology)",
    "Language",
    "World Series",
    "The Leftovers (TV series)",
    "Chicago (2002 film)",
    "Ocean",
    "Monkey (zodiac)",
    "Room (2015 film)",
    "Garbage (band)",
    "Lion (2016 film)",
    "Rocket",
    "Japan (band)",
    "Loving (2016 film)",
    "John (given name)",
    "Tympanostomy tube",
    "Fantasy",
    "Wings (1990 TV series)",
    "Friday",
    "A Movie",
    "Insects as food",
    "12-hour clock",
    "Baby (2015 Hindi film)",
    "Lion ((G)I-dle song)",
    "The Quarterback (Glee)",
    "Human taxonomy",
    "Wednesday",
    "Time (magazine)",
    "Computer program",
    "Parrot",
    "Sauce",
    "Grocery store",
    "Giant (1956 film)",
    "Kids' Choice Award for Favorite Movie",
    "COVID-19 pandemic in Mauritius",
    "The Thing (1982 film)",
    "The Sleepover",
    "Boy (2010 film)",
    "Delicious (film)",
    "Galaxy",
    "Comedy film",
    "Ai (singer)",
    "Idiot",
    "Magick (Thelema)",
    "Soccer (1985 video game)",
    "Cattle",
    "Dish (food)",
    "Pig (zodiac)",
    "Real number",
    "Goofy",
    "Fruit",
    "FaceTime",
    "Yankee",
    "The Walking Dead (TV series)",
    "Animation",
    "The Bonfire of the Vanities (film)",
    "Computer",
    "Protein (nutrient)",
    "Tag (2018 film)",
    "Cars (film)",
    "Pythonidae",
    "Dessert",
    "The News (1989 film)",
    "Boys (2003 film)",
    "Girls (TV series)",
    "Giant",
    "Camping (2006 film)",
    "College soccer",
    "Cloud",
    "Biology",
    "Dating",
    "I Kissed a Girl",
    "Full breakfast",
    "My Family",
    "My Little Pony: The Movie (1986 film)",
    "Cooking oil",
    "Loved (film)",
    "Call duck",
    "Quarterback",
    "Grounded (video game)",
    "National Football League on television",
    "Sleep",
    "Truck",
    "The Movie",
    "M.I.A. (rapper)",
    "Saturday",
    "Wanna Buakaew",
    "Singing",
    "Dig It (Beatles song)",
    "Episodes (TV series)",
    "Da 5 Bloods",
    "Tiger (guitar)",
    "Actress (musician)",
    "Cuteness",
    "Love (band)",
    "Goods",
    "Mama (TV series)",
    "Julius Caesar (1953 film)",
    "English Americans",
    "Scoob!",
    "Coming 2 America",
    "Mourning dove",
    "Monster (2003 film)",
    "Super (2010 American film)",
    "Ninja (gamer)",
    "Fast & Furious",
    "Zombies (2018 film)",
    "Artist",
    "The Mask (1994 film)",
    "Step Brothers (film)",
    "Sin: The Movie",
    "Felidae",
    "Mini (marque)",
    "Eternal Sunshine of the Spotless Mind",
    "Classical period (music)",
    "Music video",
    "Puzzle",
    "Wanted (2008 film)",
    "I Don't Want to Spoil the Party",
    "Cloud computing",
    "Mode (literature)",
    "House (1977 film)",
    "Rock paper scissors",
    "Penguin (album)",
    "Alabama (band)",
    "Kittie",
    "Rock music",
    "Lucy (2014 film)",
    "Goodfellas",
    "Robin (character)",
    "W (British TV channel)",
    "Association football",
    "Yesterday (2019 film)",
    "Zoom (software)",
    "T. Rex (band)",
    "Woman",
    "Bluetooth",
    "Airplane",
    "Stuff (website)",
    "Vacation (2015 film)",
    "Island",
    "Mom (film)",
    "Hotel",
    "Angel",
    "Danger (2005 film)",
    "Wind instrument",
    "Nana (manga)",
    "Stone Cold Crazy",
    "Thing (comics)",
    "Classical music",
    "Topic (DJ)",
    "Rabbit (zodiac)",
    "Video game industry",
    "Star",
    "Hobby",
    "Military",
    "Chemistry",
    "Kidding",
    "Dinosaur (film)",
    "GOOD Music",
    "Volume",
    "Mommy (1995 film)",
    "Monkey (character)",
    "Kinda (Doctor Who)",
    "Anna (given name)",
    "Jesus in Christianity",
    "Michael (archangel)",
    "Texture (painting)",
    "Math fab Mathonwy",
    "Meatballs (film)",
    "Batman (1989 film)",
    "Jessie (2011 TV series)",
    "Gotta Go (Chungha song)",
    "School band",
    "Tablet (confectionery)",
    "Bo (dog)",
    "Lyrics",
    "Hug",
    "Online chat",
    "Evil (TV series)",
    "Juicy (The Notorious B.I.G. song)",
    "Donald Trump (song)",
    "The Ocean (Led Zeppelin song)",
    "Guitar (song)",
    "Hectare",
    "Panda (band)",
    "Chemistry",
]
