from chirpy.core.regex.regex_template import RegexTemplate
from chirpy.core.regex.util import NONEMPTY_TEXT

REQUEST_ACTION = [
    "talk",
    "chat",
    "discuss",
    "tell",
    "show",
    "say",
    "request",
    "switch",
    "change",
    "tell me",
    "give me",
    "show me",
    "elaborate on",
    "expand on",
    "switch to",
    "change to",
    "can you tell me",
    "can you give me",
    "can you show me",
    "can you say",
    "could you tell me",
    "could you give me",
    "could you show me",
    "could you say",
    "would you tell me",
    "would you give me",
    "would you show me",
    "would you say",
    "do you know",
    "did you know",
    "how about",
    "how about we talk about",
    "how about we chat about",
    "how about we discuss",
    "let's talk about",
    "let's chat about",
    "let's discuss",
    "can we talk about",
    "can we chat about",
    "can we discuss",
    "i want to talk about",
    "i want to chat about",
    "i want to discuss",
    "i want to hear",
    "i'd like to talk about",
    "i'd like to chat about",
    "i'd like to discuss",
    "i'd like to hear",
    "i would love to talk about",
    "i would love to chat about",
    "i would love to discuss",
    "i would love to hear",
    "i'm interested in",
    "i'm curious about",
    "talk about",
    "we talk about"
]
CONTINUER = [
    "aah",
    "absolutely",
    "agreed",
    "aha",
    "ahem",
    "ahh",
    "alexa",
    "alright",
    "alrighty",
    "amen",
    "anyhoo",
    "anyhow",
    "argh",
    "awww",
    "ay",
    "bah",
    "bravo",
    "cheers",
    "eh",
    "eww",
    "gee",
    "geepers",
    "golly",
    "goodness",
    "gosh",
    "great",
    "ha",
    "ha-ha",
    "hello",
    "hey",
    "hi",
    "hmm",
    "huh",
    "hurray",
    "indeed",
    "jeez",
    "man",
    "nah",
    "no",
    "now",
    "oh",
    "ooh",
    "oops",
    "ouch",
    "ow",
    "phew",
    "phooey",
    "please",
    "pooh",
    "right-o",
    "shoot",
    "shucks",
    "so",
    "thanks",
    "um",
    "ugh",
    "uh-huh",
    "uh-oh",
    "waa",
    "wahoo",
    "well",
    "whoa",
    "whoopee",
    "whoops",
    "whoosh",
    "wow",
    "yay",
    "yea",
    "yeah",
    "yes",
    "yikes",
    "yippee",
    "yo",
    "yoo-hoo",
    "yowza",
    "yuck",
    "yummy"
]


class CategoriesTemplate(RegexTemplate):
    # TODO-Kathleen: Can we avoid using continuer and just have "{keyword}" and "{request_action} {keyword}"?
    slots = {
        'continuer': CONTINUER,
        'request_action': REQUEST_ACTION,

        # TODO-Kathleen: Might be more natural to rename this slot to 'category'.
        #  Why not have this point to categories.keys(), your list of supported categories?
        #  Then this template would only match when the user is asking for a category. Currently it matches every nonempty string!
        'keyword': NONEMPTY_TEXT,
    }
    templates = [
        "{continuer} {request_action} {keyword}",
        "{request_action} {continuer} {keyword}",
        "{continuer} {keyword}",
        "{request_action} {keyword}",
        "{keyword}",
    ]
    # TODO-Kathleen: write tests
    positive_examples = []
    negative_examples = []