from .chatty_template import ChattyTemplate
from .say_that_again_template import SayThatAgainTemplate
from .request_name_template import RequestNameTemplate
from .request_story_template import RequestStoryTemplate
from .request_play_template import RequestPlayTemplate, NotRequestPlayTemplate
from .compliment_template import ComplimentTemplate
from .request_age_template import RequestAgeTemplate