#!/bin/bash
python3.8 app.py & export APP_PID=$!
echo "Waiting for model startup"
sleep 5
while IFS='' read -r line || [[ -n "$line" ]]; do
    curl http://localhost:5001/ --header 'content-type: application/json' --data "$line" -X POST
done < "test_script"
kill -9 $APP_PID